version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5353:5353"
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --port 5353 --reload
    networks:
      - casa
networks:
  casa:
    external: true